/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaCotxe;

import ModelCotxe.ModelCotxe;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VistaCotxe extends javax.swing.JFrame {

      public String[] generar = new String[6];
    /**
     * Creates new form VistaCotxe
     */
    public VistaCotxe() {
        initComponents();
        this.jt_modelstring.setVisible(false);
        this.jt_colorstring.setVisible(false);
        this.jt_opcionsstring.setVisible(false);
        this.jt_nom.setToolTipText("Introdueix un nom");
        this.jt_telf.setToolTipText("Telèfon. 9 xifres");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jt_nom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jt_telf = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jr_blanc = new javax.swing.JRadioButton();
        jr_vermell_emocio = new javax.swing.JRadioButton();
        jr_gris = new javax.swing.JRadioButton();
        jr_negre = new javax.swing.JRadioButton();
        jr_vermell_rubi = new javax.swing.JRadioButton();
        jr_verd = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jt_total = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jt_model = new javax.swing.JTextField();
        jt_color = new javax.swing.JTextField();
        jt_opcions = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jt_modelstring = new javax.swing.JTextField();
        jt_colorstring = new javax.swing.JTextField();
        jt_opcionsstring = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nom:");

        jLabel2.setText("Telf:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Altea 1.4 TSI", "Altea 1.9 TDI Arena", "Altea 1.9 TDI DPF DSG Arena", "Altea 2.0 TDI 6 Vel. Arena", "Altea 2.0 TDI 6 Vel. DSG Arena" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jr_blanc.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jr_blanc);
        jr_blanc.setSelected(true);
        jr_blanc.setText("Blanc Candy");
        jr_blanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr_blancActionPerformed(evt);
            }
        });

        buttonGroup1.add(jr_vermell_emocio);
        jr_vermell_emocio.setText("Vermell Emoció");

        buttonGroup1.add(jr_gris);
        jr_gris.setText("Gris Zenith");

        buttonGroup1.add(jr_negre);
        jr_negre.setText("Negro Magico");

        buttonGroup1.add(jr_vermell_rubi);
        jr_vermell_rubi.setText("Vermell Rubí");

        buttonGroup1.add(jr_verd);
        jr_verd.setText("Verd Natura");

        jLabel3.setText("Model:");

        jLabel4.setText("Color:");

        jLabel5.setText("Opcions:");

        jCheckBox1.setText("Bluethooth + MP3 + antena antirrobo");

        jCheckBox2.setText("Conexión USB en apoyabrazos ");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Conexión Ipod en apoyabrazos");

        jCheckBox4.setText("Portaobjetos interior en techo con pantalla y auricular");

        jCheckBox5.setText("Portaobjetos interior en techo");

        jCheckBox6.setText("Asientos calefactados y más extras ");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setText("Sistema navegacion Blanco/negro+MP3+Antena antirrobo");

        jCheckBox8.setText("SEAT Mediasystem");

        jCheckBox9.setText("Airbags laterales");

        jCheckBox10.setText("Faros Bixenon + AFS");

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar configuració");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jt_total.setEnabled(false);

        jLabel6.setText("TOTAL");

        jt_model.setEnabled(false);

        jt_color.setEnabled(false);

        jt_opcions.setEnabled(false);

        jLabel7.setText("Preu Model");

        jLabel8.setText("Preu Pintura");

        jLabel9.setText("Preu Opcions");

        jButton3.setText("Sortir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jButton4.setText("Nou");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jt_modelstring.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel10.setText("SEAT ALTEA CONFIG GENERATOR");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaCotxe/seat.png"))); // NOI18N

        jLabel12.setText("© Copyright Seat 2017");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jt_modelstring, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jt_colorstring, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jt_opcionsstring, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(jLabel4)))
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox5)
                                    .addComponent(jCheckBox7)
                                    .addComponent(jCheckBox9))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox10)
                                    .addComponent(jCheckBox8)
                                    .addComponent(jCheckBox4)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jr_gris)
                                    .addComponent(jr_blanc)
                                    .addComponent(jr_vermell_emocio))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jr_vermell_rubi)
                                    .addComponent(jr_negre)
                                    .addComponent(jr_verd)))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jt_total)
                                    .addComponent(jt_opcions, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_color, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_model, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jt_telf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addComponent(jt_nom, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_telf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jr_blanc)
                    .addComponent(jr_negre)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jr_vermell_emocio)
                    .addComponent(jr_vermell_rubi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jr_verd)
                    .addComponent(jr_gris))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_opcions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_modelstring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_colorstring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_opcionsstring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jt_nom.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   String buttons="";
   int color=0;
   int model=0;
   int opcions=0;
   int total;
   String selmodel="";
   String selcolor="";
   String selopcions="";
   
   //SWITCH MODEL
   switch(this.jComboBox1.getSelectedItem().toString()) {
   case "Altea 1.4 TSI":
         model=21452;  
         selmodel="Altea 1.4 TSI";
   break;
   case "Altea 1.9 TDI Arena":
         model=22299;  
         selmodel="Altea 1.9 TDI Arena";
   break;
   case "Altea 1.9 TDI DPF DSG Arena":
         model=24137;
         selmodel="Altea 1.9 TDI DPF DSG Arena";
   break;
   case "Altea 2.0 TDI 6 Vel. Arena":
         model=24274;
          selmodel="Altea 2.0 TDI 6 Vel. Arena";
   break;
   case "Altea 2.0 TDI 6 Vel. DSG Arena":
         model=25741;
         selmodel="Altea 2.0 TDI 6 Vel. DSG Arena";
   break;
   }

   //IF COLOR
   if(this.jr_blanc.isSelected()==true){
   color=0;
   selcolor="Blanc Candy";
   }
   if(this.jr_vermell_emocio .isSelected()==true){
   color=150;
   selcolor="Vermell Emocio";
   }
   if (this.jr_gris.isSelected()==true){
   color=400;
   selcolor="Gris Zenith";
   }
   if (this.jr_negre.isSelected()==true){
   color=400;
   selcolor="Negre màgic";
   }
   if (this.jr_vermell_rubi.isSelected()==true){
   color=400;
   selcolor="Vermell Rubí";
   }
   if (this.jr_verd.isSelected()==true){
   color=400;
   selcolor="Verd natura";
   }
   
   
   //IF CHECKBOX
   if(this.jCheckBox1.isSelected()==true){
   opcions=opcions+276;
    selopcions=selopcions+"Bluethooth + MP3 + antena antirrobo, ";
   }
   if(this.jCheckBox2.isSelected()==true){
   opcions=opcions+100;
   selopcions=selopcions+"Conexión USB en apoyabrazos, ";
   }
   if(this.jCheckBox3.isSelected()==true){
   opcions=opcions+100;
   selopcions=selopcions+"Conexión Ipod en apoyabrazos, ";
   }
   if(this.jCheckBox4.isSelected()==true){
   opcions=opcions+369;
     selopcions=selopcions+"Portaobjetos interior en techo con pantalla y auricular, ";
   }
   if(this.jCheckBox5.isSelected()==true){
   opcions=opcions+98;
  selopcions=selopcions+"Portaobjetos interior en techo, ";
   }
   if(this.jCheckBox6.isSelected()==true){
   opcions=opcions+581;
   selopcions=selopcions+"Asientos calefactados, eyectores calefactados, lavafaros,  Montante a calefactado y retrovisores posición parking solo en reference,   ";
   }
   if(this.jCheckBox7.isSelected()==true){
   opcions=opcions+1070;
      selopcions=selopcions+"Sistema navegacion Blanco/negro+MP3+Antena antirrobo, ";
   }
   if(this.jCheckBox8.isSelected()==true){
   opcions=opcions+1465;
      selopcions=selopcions+"SEAT Mediasystem, ";
   }
   if(this.jCheckBox9.isSelected()==true){
   opcions=opcions+253;
    selopcions=selopcions+"Airbags laterales, ";
   }
   if(this.jCheckBox10.isSelected()==true){
   opcions=opcions+835;
      selopcions=selopcions+"Faros Bixenon + AFS, ";
   
   }
   
 
   
      if(this.jt_nom.getText().isEmpty()){
         JOptionPane.showMessageDialog(null,"No deixis el nom en blanc" );
   }
      else{
            try {
         int telefon=Integer.valueOf(this.jt_telf.getText());
         String telf=String.valueOf(telefon);
         if ((telf.length())==9){
        total=model+color+opcions;
   this.jt_model.setText(String.valueOf(model));
   this.jt_color.setText(String.valueOf(color));
   this.jt_opcions.setText(String.valueOf(opcions));
   this.jt_total.setText(String.valueOf(total));
   this.jTextArea1.setText("Nom :"+this.jt_nom.getText()+"\nTelèfon:"+telefon+"\nModel: "+selmodel+ "\nColor:"+selcolor+"\nOpcions: "+selopcions+"\nTOTAL: "+total);
   this.jt_modelstring.setText(selmodel);
   this.jt_colorstring.setText(selcolor);
   this.jt_opcionsstring.setText(selopcions);
   }
         else{
          JOptionPane.showMessageDialog(null,"El Telèfon ha de contenir 9 numeros" );
         }
            }
            catch (Exception e)
            {JOptionPane.showMessageDialog(null,"Introdueix nomès numeros en el camp del telèfon");}      
      }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         try {
         int telefon=Integer.valueOf(this.jt_telf.getText());
        String telf=String.valueOf(telefon);
       if((telf.length())==9){
          
    generar[0] = this.jt_nom.getText();
    generar[1] = String.valueOf(telefon);
    generar[2] = this.jt_modelstring.getText();
    generar[3] = this.jt_colorstring.getText();
    generar[4] = this.jt_opcionsstring.getText();
    generar[5] = this.jt_total.getText();  
    

    
     int verdad=1;
          int i;
    for(i=0;i<6;i++){
    if ((generar[i]).isEmpty()==true){
     verdad=0;
    }
  }
    
    if((verdad)==1){
    ModelCotxe mo = new ModelCotxe();     
     mo.EscribirFichero(generar);
     
    }
    else{ JOptionPane.showMessageDialog(null,"Generi la configuració abans de guardar-la o \nrevisi que no hi hagi valors en blanc" ); }
  }
       else{
       JOptionPane.showMessageDialog(null,"El Telèfon ha de contenir 9 numeros" );
       }
      
       }
       catch (Exception e){
           
         JOptionPane.showMessageDialog(null,"Introdueixi nomès números en el camp del Telèfon" ); 
               }
        
        
        
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jr_blancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr_blancActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jr_blancActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      //Borrar formulari
      this.jt_nom.setText("");
      this.jt_telf.setText("");
      this.jt_color.setText("");
      this.jt_model.setText("");
      this.jt_opcions.setText("");
      this.jt_total.setText("");
      this.jTextArea1.setText("");
      jComboBox1.setSelectedIndex(0);
      jr_blanc.setSelected(true);
      //Millorar amb bucle
    jCheckBox1.setSelected(false);
    jCheckBox2.setSelected(false);
    jCheckBox3.setSelected(false);
    jCheckBox4.setSelected(false);
    jCheckBox5.setSelected(false);
    jCheckBox6.setSelected(false);
    jCheckBox7.setSelected(false);
    jCheckBox8.setSelected(false);
    jCheckBox9.setSelected(false);
    jCheckBox10.setSelected(false);
      
      
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCotxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCotxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCotxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCotxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCotxe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton jr_blanc;
    private javax.swing.JRadioButton jr_gris;
    private javax.swing.JRadioButton jr_negre;
    private javax.swing.JRadioButton jr_verd;
    private javax.swing.JRadioButton jr_vermell_emocio;
    private javax.swing.JRadioButton jr_vermell_rubi;
    private javax.swing.JTextField jt_color;
    private javax.swing.JTextField jt_colorstring;
    private javax.swing.JTextField jt_model;
    private javax.swing.JTextField jt_modelstring;
    private javax.swing.JTextField jt_nom;
    private javax.swing.JTextField jt_opcions;
    private javax.swing.JTextField jt_opcionsstring;
    private javax.swing.JTextField jt_telf;
    private javax.swing.JTextField jt_total;
    // End of variables declaration//GEN-END:variables
}
